module Cinder
  class Codegen
    include AST

    BITS = {
      "i8" => 8, "i16" => 16, "i32" => 32, "i64" => 64, "i128" => 128, "i1" => 1,
    }.freeze

    def initialize(program, sema, target: "x86_64", mode: :debug)
      @program = program
      @sema = sema
      @target = target
      @target_cfg = Targets[target]
      @mode = mode
      @fns = sema.fns
      @structs = sema.structs
      @enums = sema.enums
      @consts = sema.consts
      @statics = sema.statics
      @const_types = sema.const_types
      @const_values = sema.const_values
      @statics_type = sema.statics_type
      @statics_value = sema.statics_value

      @out = []
      @entry_lines = []
      @body_lines = []
      @string_globals = []
      @t = 0
      @bb = 0
      @a = 0
      @str = 0
      @attr_group = 0
      @locals = []
      @deferred = []
      @loops = []
      @terminated = false
      @cur_block = "body"
      @current_ret_type = nil
      @used_attr_groups = {}
    end

    def generate
      emit_header
      emit_types
      emit_declares
      emit_globals
      emit_functions
      emit_string_globals
      emit_entry_wrapper
      emit_attr_groups
      @out.join("\n") + "\n"
    end

    private

    # name mangling

    PORT_IO_SPEC = {
      "outb" => { insn: "outb %al, %dx", constraints: "{dx},{al}", ret: nil },
      "outw" => { insn: "outw %ax, %dx", constraints: "{dx},{ax}", ret: nil },
      "outl" => { insn: "outl %eax, %dx", constraints: "{dx},{eax}", ret: nil },
      "inb"  => { insn: "inb %dx, %al", constraints: "={al},{dx}", ret: "i8" },
      "inw"  => { insn: "inw %dx, %ax", constraints: "={ax},{dx}", ret: "i16" },
      "inl"  => { insn: "inl %dx, %eax", constraints: "={eax},{dx}", ret: "i32" },
    }.freeze

    def port_io?(fn)
      fn.extern && PORT_IO_SPEC.key?(fn.name)
    end

    def fn_name(fn)
      return fn.name if fn.extern
      return "_start" if fn.name == "_start" && @target_cfg[:freestanding]
      "cinder_#{fn.name}"
    end

    def struct_name(name)
      "%struct.#{name}"
    end

    def static_name(name)
      "cinder_static.#{name}"
    end

    # top-level

    def emit_header
      @out << "; generated by the Cinder compiler"
      @out << "target triple = \"#{@target_cfg[:triple]}\""
      @out << "target datalayout = \"#{@target_cfg[:datalayout]}\""
    end

    def emit_types
      @structs.each_value do |s|
        next unless target_ok?(s)
        fields = s.fields.map { |f| llvm_type(f.type) }.join(", ")
        @out << "#{struct_name(s.name)} = type { #{fields} }"
      end
    end

    def emit_declares
      @out << "declare void @llvm.trap()" if @mode == :debug
      @fns.each_value do |fn|
        next unless fn.extern && target_ok?(fn)
        next if port_io?(fn)
        params = fn.params.map { |p| llvm_type(p.type) }
        params << "..." if fn.variadic
        @out << "declare #{llvm_type(fn.return_type)} @#{fn_name(fn)}(#{params.join(', ')})"
      end
    end

    def emit_globals
      @statics.each_value do |s|
        next unless target_ok?(s)
        t = @statics_type[s.name] || PrimitiveType.new(0, 0, name: "i32")
        val = @statics_value[s.name]
        section = s.section ? ", section \"#{s.section}\"" : ""
        @out << "@#{static_name(s.name)} = global #{llvm_type(t)} #{constant_for_value(val, t)}#{section}"
      end
    end

    def emit_string_globals
      @out.concat(@string_globals)
    end

    def emit_functions
      @fns.each_value do |fn|
        next unless target_ok?(fn)
        next if fn.extern
        emit_function(fn)
      end
    end

    def emit_entry_wrapper
      m = @fns["main"]
      return unless m
      unless m.params.empty? || main_signature?(m)
        raise DiagError.new(m.module_file || "<input>", m.line, m.col,
          "unsupported main signature: main takes no parameters or `argc: i32, argv: **u8`")
      end
      ret = m.return_type
      params = main_signature?(m) ? "i32 %argc, ptr %argv" : ""
      call_args = main_signature?(m) ? "(i32 %argc, ptr %argv)" : "()"
      @out << ""
      @out << "define i32 @main(#{params}) {"
      @out << "entry:"
      if ret.nil?
        @out << "  call void @cinder_main#{call_args}"
        @out << "  ret i32 0"
      elsif llvm_type(ret) == "i32"
        @out << "  %r = call i32 @cinder_main#{call_args}"
        @out << "  ret i32 %r"
      else
        @out << "  call #{llvm_type(ret)} @cinder_main#{call_args}"
        @out << "  ret i32 0"
      end
      @out << "}"
    end

    def main_signature?(m)
      return false unless m.params.length == 2
      p0, p1 = m.params
      return false unless p0.type.is_a?(PrimitiveType) && p0.type.name == "i32"
      return false unless p1.type.is_a?(PointerType) && p1.type.elem.is_a?(PointerType)
      true
    end

    def emit_attr_groups
      @used_attr_groups.each do |group, attrs|
        @out << "attributes ##{group} = { #{attrs.join(' ')} }"
      end
    end

    def target_ok?(decl)
      return true unless decl.respond_to?(:target)
      decl.target.nil? || decl.target == @target
    end

    # LLVM types

    def llvm_type(t)
      case t
      when nil then "void"
      when Sema::UNKNOWN then "void"
      when PrimitiveType
        case t.name
        when "u8", "i8" then "i8"
        when "u16", "i16" then "i16"
        when "u32", "i32" then "i32"
        when "u64", "i64" then "i64"
        when "usize", "isize" then @target_cfg[:usize]
        when "u128", "i128" then "i128"
        when "f32" then "float"
        when "f64" then "double"
        when "bool" then "i1"
        when "void" then "void"
        end
      when NamedType
        t.resolved.is_a?(EnumDecl) ? "i32" : struct_name(t.name)
      when ArrayType
        "[#{t.len_value} x #{llvm_type(t.elem)}]"
      when SliceType
        "{ ptr, i64 }"
      when PointerType
        "ptr"
      when FunctionType
        "ptr"
      when OptionalType, ErrorType
        "{ i1, #{llvm_type(t.inner)} }"
      else
        "void"
      end
    end

    def type_signed?(t)
      t.is_a?(PrimitiveType) && @sema.signed?(t.name)
    end

    def int_type?(t)
      @sema.int_type?(t)
    end

    def float_type?(t)
      @sema.float_type?(t)
    end

    def numeric_type?(t)
      int_type?(t) || float_type?(t)
    end

    def struct_type?(t)
      @sema.struct_type?(t)
    end

    def enum_type?(t)
      @sema.enum_type?(t)
    end

    def slice_type?(t)
      t.is_a?(SliceType)
    end

    def array_type?(t)
      t.is_a?(ArrayType)
    end

    def pointer_type?(t)
      t.is_a?(PointerType)
    end

    def optional_type?(t)
      t.is_a?(OptionalType) || t.is_a?(ErrorType)
    end

    def same_type?(a, b)
      a == Sema::UNKNOWN || b == Sema::UNKNOWN || @sema.equal(a, b)
    end

    # constants

    def bits(type_str)
      BITS[type_str] || 64
    end

    def int_const(value, type_str)
      if type_str == "i1"
        value == 0 ? "false" : "true"
      else
        (value & ((1 << bits(type_str)) - 1)).to_s
      end
    end

    def float_const(value, f32 = false)
      if f32
        bits = [value].pack("f").unpack1("V")
        "bitcast (i32 #{bits} to float)"
      else
        "0x" + [value].pack("G").unpack1("H*")
      end
    end

    def c_string(str)
      escaped = +""
      str.bytes.each do |b|
        case b
        when 0x22 then escaped << "\\22"
        when 0x5c then escaped << "\\5c"
        when 0x09 then escaped << "\\09"
        when 0x0a then escaped << "\\0a"
        when 0x0d then escaped << "\\0d"
        else
          if b >= 0x20 && b < 0x7f
            escaped << b.chr
          else
            escaped << format("\\%02x", b)
          end
        end
      end
      escaped
    end

    def asm_string(str)
      c_string(str)
    end

    def scalar_constant(value, t)
      case t
      when PrimitiveType
        case t.name
        when "bool" then value ? "true" : "false"
        when "f32" then float_const(value.to_f, true)
        when "f64" then float_const(value.to_f, false)
        else int_const(value, llvm_type(t))
        end
      else
        int_const(value, llvm_type(t))
      end
    end

    def constant_for_value(value, t)
      case value
      when Float then float_const(value, t && t.name == "f32")
      when Integer then scalar_constant(value, t)
      when true, false then value ? "true" : "false"
      when Array
        elem = t.is_a?(ArrayType) ? t.elem : nil
        "[#{value.map { |v| elem ? aggregate_scalar(v, elem) : v.to_s }.join(', ')}]"
      else scalar_constant(0, t)
      end
    end

    def aggregate_scalar(value, elem)
      lt = llvm_type(elem)
      case elem
      when PrimitiveType
        case elem.name
        when "bool" then value ? "true" : "false"
        when "f32", "f64" then float_const(value.to_f, elem.name == "f32")
        else "#{lt} #{int_const(value, lt)}"
        end
      else
        "#{lt} #{int_const(value, lt)}"
      end
    end

    # emission primitives 

    def emit(line)
      auto_label if @terminated
      @body_lines << "  #{line}"
    end

    def emit_alloca(line)
      @entry_lines << "  #{line}"
    end

    def emit_term(line)
      @body_lines << "  #{line}"
      @terminated = true
    end

    def emit_label(name)
      @body_lines << "#{name}:"
      @cur_block = name
      @terminated = false
    end

    def emit_branch_to(label)
      auto_label if @terminated
      emit_term("br label %#{label}")
    end

    def auto_label
      @cur_block = "bb.#{@bb += 1}"
      @body_lines << "#{@cur_block}:"
      @terminated = false
    end

    def instr(text)
      auto_label if @terminated
      n = "%t.#{@t += 1}"
      @body_lines << "  #{n} = #{text}"
      n
    end

    def instr_named(name, text)
      auto_label if @terminated
      @body_lines << "  %#{name} = #{text}"
      "%#{name}"
    end

    def load_value(type, ptr, volatile: false)
      instr("load#{volatile ? ' volatile' : ''} #{llvm_type(type)}, ptr #{ptr}")
    end

    def store_value(type, value, ptr, volatile: false)
      emit("store#{volatile ? ' volatile' : ''} #{llvm_type(type)} #{value}, ptr #{ptr}")
    end

    # functions

    def emit_function(fn)
      ret_type = fn.return_type
      params = fn.params.map { |p| llvm_type(p.type) }
      @entry_lines = []
      @body_lines = []
      @t = 0
      @a = 0
      @deferred = []
      @loops = []
      @terminated = false
      @cur_block = "body"
      @current_ret_type = ret_type
      @locals = [{}]

      attrs = fn_attrs(fn)
      @out << ""
      decl = "define #{llvm_type(ret_type)} @#{fn_name(fn)}(#{params.join(', ')})"
      decl << " section \"#{fn.section}\"" if fn.section
      if attrs && !attrs.empty?
        @attr_group += 1
        @used_attr_groups[@attr_group] = attrs
        decl << " ##{@attr_group}"
      end
      @out << "#{decl} {"

      fn.params.each_with_index do |p, i|
        ptr = alloca(p.name, p.type)
        store_value(p.type, "%#{i}", ptr)
        define_local(p.name, ptr, p.type)
      end

      stmts = fn.body.stmts
      last = stmts.last
      if ret_type && last.is_a?(ExprStmt) && !last.terminated
        stmts[0...-1].each { |s| gen_stmt(s) }
        v = gen_as(last.expr, ret_type)
        emit_defers
        emit_term("ret #{llvm_type(ret_type)} #{v}")
      else
        stmts.each { |s| gen_stmt(s) }
        unless @terminated
          emit_defers
          if ret_type
            emit_term("ret #{llvm_type(ret_type)} zeroinitializer")
          else
            emit_term("ret void")
          end
        end
      end

      @out << "entry:"
      @out.concat(@entry_lines)
      @out << "  br label %body"
      @out << "body:"
      @out.concat(@body_lines)
      @out << "}"
    end

    def fn_attrs(fn)
      attrs = []
      attrs << "alwaysinline" if fn.inline
      attrs << "naked" if fn.naked
      attrs << "noreturn" if fn.noreturn
      attrs << 'noredzone' if @target_cfg[:freestanding]
      attrs
    end

    def alloca(name, type)
      ptr = "%p.#{name}.#{@a += 1}"
      emit_alloca("#{ptr} = alloca #{llvm_type(type)}")
      ptr
    end

    def define_local(name, ptr, type)
      @locals.last[name] = { ptr: ptr, type: type }
    end

    def lookup_local(name)
      @locals.reverse_each { |sc| return sc[name] if sc.key?(name) }
      nil
    end

    def push_scope
      @locals << {}
    end

    def pop_scope
      @locals.pop
    end

    def push_loop(latch, exit_label)
      @loops << { latch: latch, exit: exit_label }
    end

    def pop_loop
      @loops.pop
    end

    def scope_snapshot
      @locals.map { |s| s.dup }
    end

    def emit_defers
      saved = @locals
      @deferred.reverse_each do |stmt, snapshot|
        @locals = snapshot
        gen_stmt(stmt)
      end
    ensure
      @locals = saved
    end

    # statements

    def gen_stmt(node)
      case node
      when Block
        push_scope
        node.stmts.each { |s| gen_stmt(s) }
        pop_scope
      when LetStmt
        lt = let_type(node)
        ptr = alloca(node.name, lt)
        v = gen_as(node.init, lt)
        store_value(lt, v, ptr)
        define_local(node.name, ptr, lt)
      when AssignStmt
        gen_assign(node)
      when IfStmt
        gen_if_stmt(node)
      when WhileStmt
        gen_while(node)
      when LoopStmt
        gen_loop(node)
      when ForRangeStmt
        gen_for_range(node)
      when ForIterStmt
        gen_for_iter(node)
      when SwitchStmt
        gen_switch(node)
      when ReturnStmt
        gen_return(node)
      when BreakStmt
        emit_term("br label %#{@loops.last[:exit]}") if @loops.last
      when ContinueStmt
        emit_term("br label %#{@loops.last[:latch]}") if @loops.last
      when DeferStmt
        @deferred << [node.stmt, scope_snapshot]
      when UnsafeBlock
        push_scope
        node.block.stmts.each { |s| gen_stmt(s) }
        pop_scope
      when AsmStmt
        emit("call void asm sideeffect \"#{asm_string(node.asm_string)}\", \"\"()")
      when StaticAssertStmt
        # compile-time only, no runtime code
      when ExprStmt
        gen_expr(node.expr)
      end
    end

    def let_type(node)
      if node.type_annot
        node.type_annot
      else
        node.init.sema_type
      end
    end

    def gen_assign(node)
      ptr = gen_addr(node.target)
      return if ptr.nil?
      tt = node.target.sema_type
      volatile = volatile_through?(node.target)
      case node.op
      when "="
        v = gen_as(node.value, tt)
        store_value(tt, v, ptr, volatile: volatile)
      else
        cur = load_value(tt, ptr, volatile: volatile)
        vt = gen_as(node.value, tt)
        res = binary_op_value(node.op[0..-2], tt, cur, vt)
        store_value(tt, res, ptr, volatile: volatile)
      end
    end

    def gen_if_stmt(node)
      c = gen_as(node.cond, @sema.bool_type)
      n = @bb += 1
      emit_term("br i1 #{c}, label %if_then.#{n}, label %if_else.#{n}")
      emit_label("if_then.#{n}")
      push_scope
      node.then_block.stmts.each { |s| gen_stmt(s) }
      pop_scope
      emit_branch_to("if_end.#{n}")
      emit_label("if_else.#{n}")
      node.elifs.each do |cond, block|
        m = @bb += 1
        c2 = gen_as(cond, @sema.bool_type)
        emit_term("br i1 #{c2}, label %if_elif.#{m}, label %if_else2.#{m}")
        emit_label("if_elif.#{m}")
        push_scope
        block.stmts.each { |s| gen_stmt(s) }
        pop_scope
        emit_branch_to("if_end.#{n}")
        emit_label("if_else2.#{m}")
      end
      if node.else_block
        push_scope
        node.else_block.stmts.each { |s| gen_stmt(s) }
        pop_scope
      end
      emit_branch_to("if_end.#{n}")
      emit_label("if_end.#{n}")
    end

    def gen_while(node)
      n = @bb += 1
      emit("br label %while_head.#{n}")
      emit_label("while_head.#{n}")
      c = gen_as(node.cond, @sema.bool_type)
      emit_term("br i1 #{c}, label %while_body.#{n}, label %while_end.#{n}")
      emit_label("while_body.#{n}")
      push_scope
      push_loop("while_head.#{n}", "while_end.#{n}")
      node.body.stmts.each { |s| gen_stmt(s) }
      pop_loop
      pop_scope
      emit_branch_to("while_head.#{n}")
      emit_label("while_end.#{n}")
    end

    def gen_loop(node)
      n = @bb += 1
      emit("br label %loop_body.#{n}")
      emit_label("loop_body.#{n}")
      push_scope
      push_loop("loop_body.#{n}", "loop_end.#{n}")
      node.body.stmts.each { |s| gen_stmt(s) }
      pop_loop
      pop_scope
      emit_branch_to("loop_body.#{n}")
      emit_label("loop_end.#{n}")
    end

    def gen_for_range(node)
      rng = node.range
      rt = range_type(rng)
      n = @bb += 1
      start = gen_as(rng.start, rt)
      finish = gen_as(rng.end_, rt)
      ptr = alloca(node.var, rt)
      define_local(node.var, ptr, rt)

      entry = @cur_block
      emit("br label %for_head.#{n}")
      emit_label("for_head.#{n}")
      i = instr("phi #{llvm_type(rt)} [#{start}, %#{entry}], [%for_next.#{n}, %for_latch.#{n}]")
      c = range_compare(i, finish, rt, rng.inclusive)
      emit_term("br i1 #{c}, label %for_body.#{n}, label %for_exit.#{n}")
      emit_label("for_body.#{n}")
      store_value(rt, i, ptr)

      push_scope
      push_loop("for_latch.#{n}", "for_exit.#{n}")
      node.body.stmts.each { |s| gen_stmt(s) }
      pop_loop
      pop_scope
      emit_branch_to("for_latch.#{n}")
      emit_label("for_latch.#{n}")
      instr_named("for_next.#{n}", "add #{llvm_type(rt)} #{i}, 1")
      emit_term("br label %for_head.#{n}")
      emit_label("for_exit.#{n}")
    end

    def gen_for_iter(node)
      t = node.iterable.sema_type
      n = @bb += 1
      if slice_type?(t)
        s = gen_expr(node.iterable)
        base = instr("extractvalue { ptr, i64 } #{s}, 0")
        len = instr("extractvalue { ptr, i64 } #{s}, 1")
      else
        base = gen_addr(node.iterable)
        len = t.len_value.to_s
      end

      idx_ptr = alloca(node.index_var, usize_type) if node.index_var
      val_ptr = alloca(node.value_var, t.elem)
      push_scope
      define_local(node.index_var, idx_ptr, usize_type) if node.index_var
      define_local(node.value_var, val_ptr, t.elem)

      entry = @cur_block
      emit("br label %for_iter_head.#{n}")
      emit_label("for_iter_head.#{n}")
      i = instr("phi i64 [0, %#{entry}], [%iter_next.#{n}, %iter_latch.#{n}]")
      c = instr("icmp ult i64 #{i}, #{len}")
      emit_term("br i1 #{c}, label %iter_body.#{n}, label %iter_exit.#{n}")
      emit_label("iter_body.#{n}")

      if slice_type?(t)
        ep = instr("getelementptr #{llvm_type(t.elem)}, ptr #{base}, i64 #{i}")
      else
        ep = instr("getelementptr #{llvm_type(t)}, ptr #{base}, i64 0, i64 #{i}")
      end
      ev = load_value(t.elem, ep)
      store_value(usize_type, i, idx_ptr) if node.index_var
      store_value(t.elem, ev, val_ptr)

      push_loop("iter_latch.#{n}", "iter_exit.#{n}")
      node.body.stmts.each { |s| gen_stmt(s) }
      pop_loop
      pop_scope
      emit_branch_to("iter_latch.#{n}")
      emit_label("iter_latch.#{n}")
      instr_named("iter_next.#{n}", "add i64 #{i}, 1")
      emit_term("br label %for_iter_head.#{n}")
      emit_label("iter_exit.#{n}")
    end

    def range_compare(i, finish, rt, inclusive)
      if float_type?(rt)
        instr("fcmp #{inclusive ? "ole" : "olt"} #{llvm_type(rt)} #{i}, #{finish}")
      else
        instr("icmp #{cmp_pred(inclusive ? "<=" : "<", rt)} #{llvm_type(rt)} #{i}, #{finish}")
      end
    end

    def gen_switch(node)
      st = node.subject.sema_type
      subj = gen_as(node.subject, st)
      n = @bb += 1
      emit("br label %sw.#{n}")
      emit_label("sw.#{n}")
      node.cases.each_with_index do |c, i|
        cond = switch_pattern_cond(c.pattern, st, subj)
        emit_term("br i1 #{cond}, label %sw_body.#{i}.#{n}, label %sw_next.#{i + 1}.#{n}")
        emit_label("sw_body.#{i}.#{n}")
        push_scope
        c.body.stmts.each { |s| gen_stmt(s) }
        pop_scope
        emit_branch_to("sw_end.#{n}")
        emit_label("sw_next.#{i + 1}.#{n}")
      end
      if node.else_block
        emit_branch_to("sw_else.#{n}")
        emit_label("sw_else.#{n}")
        push_scope
        node.else_block.stmts.each { |s| gen_stmt(s) }
        pop_scope
        emit_branch_to("sw_end.#{n}")
      else
        emit_branch_to("sw_end.#{n}")
      end
      emit_label("sw_end.#{n}")
    end

    def switch_pattern_cond(pat, st, subj)
      case pat
      when RangeExpr
        lo = gen_as(pat.start, st)
        hi = gen_as(pat.end_, st)
        p1 = instr("icmp #{cmp_pred(">=", st)} #{llvm_type(st)} #{subj}, #{lo}")
        p2 = instr("icmp #{cmp_pred(pat.inclusive ? "<=" : "<", st)} #{llvm_type(st)} #{subj}, #{hi}")
        instr("and i1 #{p1}, #{p2}")
      when EnumValueExpr, FieldAccessExpr
        idx = enum_pattern_index(pat, st)
        instr("icmp eq i32 #{subj}, #{idx}")
      else
        c = gen_as(pat, st)
        instr("icmp eq #{llvm_type(st)} #{subj}, #{c}")
      end
    end

    def gen_return(node)
      rt = @current_ret_type
      if node.value
        v = gen_as(node.value, rt)
        emit_defers
        emit_term("ret #{llvm_type(rt)} #{v}")
      else
        emit_defers
        emit_term("ret void")
      end
    end

    # expressions

    def gen_expr(node)
      case node
      when IntLiteral, CharLiteral, BoolLiteral
        literal_operand(node, node.sema_type)
      when FloatLiteral
        t = node.sema_type
        float_const(node.value, t && t.name == "f32")
      when StringLiteral
        gen_string_literal(node)
      when NoneLiteral, NullLiteral
        raise "internal: literal #{node.class} without expected type in codegen"
      when ArrayLiteralExpr
        gen_array_literal(node)
      when VarExpr
        gen_var(node)
      when UnaryExpr
        gen_unary(node)
      when BinaryExpr
        gen_binary(node)
      when CastExpr
        gen_cast(node)
      when CallExpr
        gen_call(node)
      when IndexExpr
        gen_index(node)
      when SliceExpr
        gen_slice(node)
      when FieldAccessExpr
        gen_field(node)
      when StructInitExpr
        gen_struct_init(node)
      when EnumValueExpr
        enum_variant_index(node)
      when IfExpr
        gen_if_expr(node)
      when OptionalElseExpr
        gen_maybe_else(node)
      when ErrorUnwrapExpr
        gen_unwrap(node)
      when SizeofExpr, AlignofExpr, OffsetofExpr
        int_const(node.value, "usize")
      when AsmExpr
        emit("call void asm sideeffect \"#{asm_string(node.asm_string)}\", \"\"()")
        "void"
      else
        "void"
      end
    end

    def gen_as(node, expected)
      t = node.sema_type
      if (expected.nil? || same_type?(t, expected)) &&
         !(node.is_a?(NoneLiteral) || node.is_a?(NullLiteral))
        return gen_expr(node)
      end

      inner = optional_type?(expected) ? expected.inner : expected

      case node
      when IntLiteral, FloatLiteral, CharLiteral, BoolLiteral
        if numeric_type?(inner)
          v = literal_operand(node, inner)
          return optional_type?(expected) ? wrap_opt(expected, v) : v
        end
      when NoneLiteral
        if optional_type?(expected)
          return pair_const(expected)
        end
      when NullLiteral
        if pointer_type?(expected) || expected.is_a?(FunctionType)
          return "null"
        end
      when StringLiteral
        if expected.is_a?(SliceType) || pointer_type?(expected)
          return gen_string_literal(node, expected)
        end
      when ArrayLiteralExpr
        if array_type?(expected)
          return gen_array_literal(node, expected)
        end
      when VarExpr
        if @consts.key?(node.name) && numeric_type?(inner) && numeric_type?(t)
          v = const_converted(node.name, inner)
          return optional_type?(expected) ? wrap_opt(expected, v) : v
        end
      end

      # wrap T into ?T / !T
      if optional_type?(expected) && same_type?(t, inner)
        v = gen_expr(node)
        return wrap_opt(expected, v)
      end

      # error enum return in !T fn
      if expected.is_a?(ErrorType) && enum_type?(t)
        v = gen_expr(node)
        return err_pair(expected, v, t)
      end

      # lossless int widening (u8 -> u32, i8 -> i64, i32 -> usize, ...)
      if int_type?(t) && int_type?(inner) &&
         @sema.int_rank(t.name) <= @sema.int_rank(inner.name)
        v = gen_expr(node)
        return int_extend(v, t, inner)
      end

      gen_expr(node)
    end

    def literal_operand(node, t)
      if t.is_a?(PrimitiveType) && t.name == "bool"
        node.value ? "true" : "false"
      elsif int_type?(t)
        val = node.is_a?(BoolLiteral) ? (node.value ? 1 : 0) : node.value
        int_const(val, llvm_type(t))
      elsif float_type?(t)
        val = node.is_a?(FloatLiteral) ? node.value : node.value.to_f
        float_const(val, t.name == "f32")
      else
        gen_expr(node)
      end
    end

    def int_extend(v, from, to)
      return v if llvm_type(from) == llvm_type(to)
      instr("#{@sema.signed?(from.name) ? "sext" : "zext"} #{llvm_type(from)} #{v} to #{llvm_type(to)}")
    end

    def pair_const(expected)
      instr("insertvalue #{llvm_type(expected)} zeroinitializer, i1 false, 0")
    end

    def wrap_opt(expected, v)
      r = instr("insertvalue #{llvm_type(expected)} zeroinitializer, i1 true, 0")
      instr("insertvalue #{llvm_type(expected)} #{r}, #{llvm_type(expected.inner)} #{v}, 1")
    end

    def err_pair(expected, v, src_type)
      r = instr("insertvalue #{llvm_type(expected)} zeroinitializer, i1 false, 0")
      conv = int_convert(v, src_type, expected.inner)
      instr("insertvalue #{llvm_type(expected)} #{r}, #{llvm_type(expected.inner)} #{conv}, 1")
    end

    def int_convert(v, from, to)
      return v unless int_type?(to)
      fb = bits(llvm_type(from))
      tb = bits(llvm_type(to))
      if tb < fb
        instr("trunc #{llvm_type(from)} #{v} to #{llvm_type(to)}")
      elsif tb > fb
        instr("#{@sema.signed?(from.is_a?(PrimitiveType) ? from.name : "i32") ? "sext" : "zext"} #{llvm_type(from)} #{v} to #{llvm_type(to)}")
      else
        v
      end
    end

    def const_converted(name, expected)
      v = @const_values[name]
      if int_type?(expected)
        int_const(v, llvm_type(expected))
      elsif float_type?(expected)
        float_const(v.to_f, expected.name == "f32")
      end
    end

    def gen_var(node)
      name = node.name
      if (loc = lookup_local(name))
        return load_value(loc[:type], loc[:ptr])
      end
      if @statics.key?(name)
        return load_value(@statics_type[name], "@#{static_name(name)}")
      end
      if @consts.key?(name)
        ct = @const_types[name]
        return scalar_constant(@const_values[name], ct)
      end
      if (fn = @fns[name])
        return "void" if port_io?(fn)
        return "@#{fn_name(fn)}"
      end
      "void"
    end

    def gen_string_literal(node, expected = nil)
      s = node.value
      data_name = "@cinder_str.#{@str += 1}"
      @string_globals << "#{data_name} = private unnamed_addr constant [#{s.bytesize + 1} x i8] c\"#{c_string(s + "\u0000")}\""
      if node.kind == :cstring || pointer_type?(expected)
        instr("getelementptr [#{s.bytesize + 1} x i8], ptr #{data_name}, i64 0, i64 0")
      else
        p = instr("getelementptr [#{s.bytesize + 1} x i8], ptr #{data_name}, i64 0, i64 0")
        r = instr("insertvalue { ptr, i64 } zeroinitializer, ptr #{p}, 0")
        instr("insertvalue { ptr, i64 } #{r}, i64 #{s.bytesize}, 1")
      end
    end

    def gen_array_literal(node, expected = nil)
      arr_type = expected || node.sema_type
      elem = arr_type.elem
      ptr = alloca("arr", arr_type)
      if node.repeat
        count = node.repeat_len || 0
        v = gen_as(node.elements[0], elem)
        if count > 0
          n = @bb += 1
          entry = @cur_block
          emit("br label %rep_head.#{n}")
          emit_label("rep_head.#{n}")
          i = instr("phi i64 [0, %#{entry}], [%rep_next.#{n}, %rep_latch.#{n}]")
          c = instr("icmp ult i64 #{i}, #{count}")
          emit_term("br i1 #{c}, label %rep_body.#{n}, label %rep_end.#{n}")
          emit_label("rep_body.#{n}")
          ep = instr("getelementptr #{llvm_type(arr_type)}, ptr #{ptr}, i64 0, i64 #{i}")
          store_value(elem, v, ep)
          emit_branch_to("rep_latch.#{n}")
          emit_label("rep_latch.#{n}")
          instr_named("rep_next.#{n}", "add i64 #{i}, 1")
          emit_branch_to("rep_head.#{n}")
          emit_label("rep_end.#{n}")
        end
      else
        node.elements.each_with_index do |el, i|
          v = gen_as(el, elem)
          ep = instr("getelementptr #{llvm_type(arr_type)}, ptr #{ptr}, i64 0, i64 #{i}")
          store_value(elem, v, ep)
        end
      end
      load_value(arr_type, ptr)
    end

    def gen_unary(node)
      case node.op
      when "-"
        t = node.operand.sema_type
        v = gen_as(node.operand, t)
        if float_type?(t)
          instr("fneg #{llvm_type(t)} #{v}")
        else
          instr("sub #{llvm_type(t)} 0, #{v}")
        end
      when "!"
        v = gen_as(node.operand, @sema.bool_type)
        instr("xor i1 #{v}, true")
      when "&"
        gen_addr(node.operand) || (raise "internal: cannot take address")
      when "*"
        t = node.operand.sema_type
        v = gen_as(node.operand, t)
        load_value(t.elem, v, volatile: t.is_a?(PointerType) && t.volatile)
      end
    end

    def gen_binary(node)
      op = node.op
      return gen_logic(node) if op == "&&" || op == "||"

      lt = node.lhs.sema_type
      t = node.sema_type

      if pointer_type?(lt) && (op == "+" || op == "-")
        base = gen_as(node.lhs, lt)
        idx = gen_as(node.rhs, usize_type)
        idx = instr("sub i64 0, #{idx}") if op == "-"
        return instr("getelementptr #{llvm_type(lt.elem)}, ptr #{base}, i64 #{idx}")
      end
      if pointer_type?(node.rhs.sema_type) && op == "+"
        rt2 = node.rhs.sema_type
        base = gen_as(node.rhs, rt2)
        idx = gen_as(node.lhs, usize_type)
        return instr("getelementptr #{llvm_type(rt2.elem)}, ptr #{base}, i64 #{idx}")
      end

      case op
      when "==", "!=", "<", "<=", ">", ">="
        cmp_t = comparison_type(lt, node.rhs.sema_type)
        a = gen_as(node.lhs, cmp_t)
        b = gen_as(node.rhs, cmp_t)
        binary_op_value(op, cmp_t, a, b)
      else
        a = gen_as(node.lhs, t)
        b = gen_as(node.rhs, t)
        binary_op_value(op, t, a, b)
      end
    end

    def comparison_type(a, b)
      return a if same_type?(a, b)
      if numeric_type?(a) && numeric_type?(b)
        return b if int_type?(a) && float_type?(b)
        return a if float_type?(a) && int_type?(b)
        return a if float_type?(a) && float_type?(b)
        if int_type?(a) && int_type?(b) && @sema.signed?(a.name) == @sema.signed?(b.name)
          return @sema.int_rank(a.name) >= @sema.int_rank(b.name) ? a : b
        end
      end
      a
    end

    def binary_op_value(op, t, a, b)
      case op
      when "+", "-", "*", "/", "%"
        arith_op(op, t, a, b)
      when "<<"
        instr("shl #{llvm_type(t)} #{a}, #{b}")
      when ">>"
        instr("#{type_signed?(t) ? "ashr" : "lshr"} #{llvm_type(t)} #{a}, #{b}")
      when "&"
        instr("and #{llvm_type(t)} #{a}, #{b}")
      when "|"
        instr("or #{llvm_type(t)} #{a}, #{b}")
      when "^"
        instr("xor #{llvm_type(t)} #{a}, #{b}")
      when "==", "!="
        compare_op(op, t, a, b)
      when "<", "<=", ">", ">="
        if float_type?(t)
          instr("fcmp #{cmp_pred(op, t)} #{llvm_type(t)} #{a}, #{b}")
        else
          instr("icmp #{cmp_pred(op, t)} #{llvm_type(t)} #{a}, #{b}")
        end
      end
    end

    def arith_op(op, t, a, b)
      if float_type?(t)
        case op
        when "+" then instr("fadd #{llvm_type(t)} #{a}, #{b}")
        when "-" then instr("fsub #{llvm_type(t)} #{a}, #{b}")
        when "*" then instr("fmul #{llvm_type(t)} #{a}, #{b}")
        when "/" then instr("fdiv #{llvm_type(t)} #{a}, #{b}")
        when "%" then instr("frem #{llvm_type(t)} #{a}, #{b}")
        end
      else
        s = type_signed?(t)
        case op
        when "+" then instr("add #{llvm_type(t)} #{a}, #{b}")
        when "-" then instr("sub #{llvm_type(t)} #{a}, #{b}")
        when "*" then instr("mul #{llvm_type(t)} #{a}, #{b}")
        when "/" then instr("#{s ? "sdiv" : "udiv"} #{llvm_type(t)} #{a}, #{b}")
        when "%" then instr("#{s ? "srem" : "urem"} #{llvm_type(t)} #{a}, #{b}")
        end
      end
    end

    def compare_op(op, t, a, b)
      if pointer_type?(t)
        instr("icmp #{op == "==" ? "eq" : "ne"} ptr #{a}, #{b}")
      elsif optional_type?(t)
        fa = instr("extractvalue #{llvm_type(t)} #{a}, 0")
        fb = instr("extractvalue #{llvm_type(t)} #{b}, 0")
        flag_eq = instr("icmp eq i1 #{fa}, #{fb}")
        va = instr("extractvalue #{llvm_type(t)} #{a}, 1")
        vb = instr("extractvalue #{llvm_type(t)} #{b}, 1")
        if float_type?(t.inner)
          val = instr("fcmp #{op == "==" ? "oeq" : "une"} #{llvm_type(t.inner)} #{va}, #{vb}")
        else
          val = instr("icmp #{op == "==" ? "eq" : "ne"} #{llvm_type(t.inner)} #{va}, #{vb}")
        end
        if op == "=="
          instr("and i1 #{flag_eq}, #{val}")
        else
          flag_ne = instr("xor i1 #{flag_eq}, true")
          instr("or i1 #{flag_ne}, #{val}")
        end
      elsif float_type?(t)
        instr("fcmp #{op == "==" ? "oeq" : "one"} #{llvm_type(t)} #{a}, #{b}")
      else
        instr("icmp #{op == "==" ? "eq" : "ne"} #{llvm_type(t)} #{a}, #{b}")
      end
    end

    def cmp_pred(op, t)
      if float_type?(t)
        { "<" => "olt", "<=" => "ole", ">" => "ogt", ">=" => "oge" }[op]
      else
        s = type_signed?(t)
        {
          "<" => s ? "slt" : "ult",
          "<=" => s ? "sle" : "ule",
          ">" => s ? "sgt" : "ugt",
          ">=" => s ? "sge" : "uge",
        }[op]
      end
    end

    def gen_logic(node)
      n = @bb += 1
      a = gen_as(node.lhs, @sema.bool_type)
      if node.op == "&&"
        emit_term("br i1 #{a}, label %and_rhs.#{n}, label %and_res.#{n}")
        pred1 = @cur_block
        emit_label("and_rhs.#{n}")
        b = gen_as(node.rhs, @sema.bool_type)
        emit_branch_to("and_res.#{n}")
        pred2 = @cur_block
        emit_label("and_res.#{n}")
        instr("phi i1 [#{a}, %#{pred1}], [#{b}, %#{pred2}]")
      else
        emit_term("br i1 #{a}, label %or_res.#{n}, label %or_rhs.#{n}")
        pred1 = @cur_block
        emit_label("or_rhs.#{n}")
        b = gen_as(node.rhs, @sema.bool_type)
        emit_branch_to("or_res.#{n}")
        pred2 = @cur_block
        emit_label("or_res.#{n}")
        instr("phi i1 [#{a}, %#{pred1}], [#{b}, %#{pred2}]")
      end
    end

    def gen_cast(node)
      src = node.expr.sema_type
      dst = node.type
      v = gen_as(node.expr, src)
      convert_value(v, src, dst)
    end

    def convert_value(v, src, dst)
      return v if same_type?(src, dst)
      if int_type?(src) && int_type?(dst)
        sb = bits(llvm_type(src))
        db = bits(llvm_type(dst))
        return instr("trunc #{llvm_type(src)} #{v} to #{llvm_type(dst)}") if db < sb
        return instr("#{@sema.signed?(src.name) ? "sext" : "zext"} #{llvm_type(src)} #{v} to #{llvm_type(dst)}") if db > sb
        return v
      end
      if int_type?(src) && float_type?(dst)
        return instr("#{@sema.signed?(src.name) ? "sitofp" : "uitofp"} #{llvm_type(src)} #{v} to #{llvm_type(dst)}")
      end
      if float_type?(src) && int_type?(dst)
        return instr("#{@sema.signed?(dst.name) ? "fptosi" : "fptoui"} #{llvm_type(src)} #{v} to #{llvm_type(dst)}")
      end
      if float_type?(src) && float_type?(dst)
        sb = bits(llvm_type(src))
        db = bits(llvm_type(dst))
        return instr("fptrunc #{llvm_type(src)} #{v} to #{llvm_type(dst)}") if db < sb
        return instr("fpext #{llvm_type(src)} #{v} to #{llvm_type(dst)}")
      end
      if pointer_type?(src) && int_type?(dst)
        return instr("ptrtoint #{llvm_type(src)} #{v} to #{llvm_type(dst)}")
      end
      if int_type?(src) && pointer_type?(dst)
        return instr("inttoptr #{llvm_type(src)} #{v} to #{llvm_type(dst)}")
      end
      v
    end

    def gen_call(node)
      callee = node.callee
      if callee.is_a?(VarExpr) && (fn = @fns[callee.name])
        return gen_port_io(fn, fn.params.zip(node.args).map { |p, a| "#{llvm_type(p.type)} #{gen_as(a, p.type)}" }) if port_io?(fn)
        return gen_direct_call(node, fn)
      end
      gen_indirect_call(node)
    end

    def gen_direct_call(node, fn)
      fixed = fn.params.zip(node.args).map { |p, a| "#{llvm_type(p.type)} #{gen_as(a, p.type)}" }
      variadic = node.args[fn.params.length..] || []
      args = fixed + variadic.map do |a|
        v = gen_expr(a)
        "#{llvm_type(a.sema_type)} #{v}"
      end
      ret = fn.return_type
      ftype = "#{llvm_type(ret)} (#{fn.params.map { |p| llvm_type(p.type) }.join(', ')}#{fn.variadic ? ', ...' : ''})"
      if ret.nil?
        emit("call #{ftype} @#{fn_name(fn)}(#{args.join(', ')})")
        "void"
      else
        instr("call #{ftype} @#{fn_name(fn)}(#{args.join(', ')})")
      end
    end

    def gen_indirect_call(node)
      ft = node.callee.sema_type.is_a?(FunctionType) ? node.callee.sema_type : node.sema_type.is_a?(FunctionType) ? node.sema_type : nil
      raise "internal: indirect call without a function type" if ft.nil?
      fp = gen_as(node.callee, ft)
      args = ft.params.zip(node.args).map { |p, a| "#{llvm_type(p)} #{gen_as(a, p)}" }
      ftype = "#{llvm_type(ft.ret)} (#{ft.params.map { |p| llvm_type(p) }.join(', ')})"
      if ft.ret.nil?
        emit("call #{ftype} #{fp}(#{args.join(', ')})")
        "void"
      else
        instr("call #{ftype} #{fp}(#{args.join(', ')})")
      end
    end

    def gen_port_io(fn, args)
      spec = PORT_IO_SPEC[fn.name]
      asm = "call #{spec[:ret] || 'void'} asm sideeffect \"#{spec[:insn]}\", \"#{spec[:constraints]}\"(#{args.join(', ')})"
      if spec[:ret].nil?
        emit(asm)
        "void"
      else
        instr(asm)
      end
    end

    def gen_index(node)
      tt = node.target.sema_type
      if slice_type?(tt)
        s = gen_expr(node.target)
        base = instr("extractvalue { ptr, i64 } #{s}, 0")
        len = instr("extractvalue { ptr, i64 } #{s}, 1")
        idx = gen_as(node.index, usize_type)
        emit_bounds_check(idx, len) if @mode == :debug
        ep = instr("getelementptr #{llvm_type(tt.elem)}, ptr #{base}, i64 #{idx}")
        return load_value(tt.elem, ep)
      end
      if array_type?(tt)
        base = gen_addr(node.target)
        idx = gen_as(node.index, usize_type)
        if @mode == :debug && tt.len_value
          emit_bounds_check(idx, tt.len_value.to_s)
        end
        ep = instr("getelementptr #{llvm_type(tt)}, ptr #{base}, i64 0, i64 #{idx}")
        return load_value(tt.elem, ep)
      end
      if pointer_type?(tt)
        base = gen_expr(node.target)
        idx = gen_as(node.index, usize_type)
        ep = instr("getelementptr #{llvm_type(tt.elem)}, ptr #{base}, i64 #{idx}")
        return load_value(tt.elem, ep, volatile: tt.volatile)
      end
      "void"
    end

    def emit_bounds_check(idx, len)
      n = @bb += 1
      c = instr("icmp ult i64 #{idx}, #{len}")
      emit_term("br i1 #{c}, label %bnd_ok.#{n}, label %bnd_trap.#{n}")
      emit_label("bnd_trap.#{n}")
      emit("call void @llvm.trap()")
      emit_term("unreachable")
      emit_label("bnd_ok.#{n}")
    end

    def gen_slice(node)
      tt = node.target.sema_type
      elem = tt.elem
      if slice_type?(tt)
        s = gen_expr(node.target)
        base = instr("extractvalue { ptr, i64 } #{s}, 0")
        len = instr("extractvalue { ptr, i64 } #{s}, 1")
        return make_slice(base, node.start, node.end_, len, elem)
      end
      if array_type?(tt)
        base = gen_addr(node.target)
        return make_slice(base, node.start, node.end_, tt.len_value.to_s, elem, array: tt)
      end
      if pointer_type?(tt)
        base = gen_expr(node.target)
        return make_slice(base, node.start, node.end_, "0", elem)
      end
      "void"
    end

    def make_slice(base, start_node, end_node, len_operand, elem, array: nil)
      start = start_node ? gen_as(start_node, usize_type) : "0"
      stop = end_node ? gen_as(end_node, usize_type) : len_operand
      p =
        if array
          instr("getelementptr #{llvm_type(array)}, ptr #{base}, i64 0, i64 #{start}")
        else
          instr("getelementptr #{llvm_type(elem)}, ptr #{base}, i64 #{start}")
        end
      l = instr("sub i64 #{stop}, #{start}")
      r = instr("insertvalue { ptr, i64 } zeroinitializer, ptr #{p}, 0")
      instr("insertvalue { ptr, i64 } #{r}, i64 #{l}, 1")
    end

    def gen_field(node)
      tt = node.target.sema_type
      if slice_type?(tt)
        s = gen_expr(node.target)
        return instr("extractvalue { ptr, i64 } #{s}, #{node.field == "len" ? 1 : 0}")
      end
      if enum_type?(tt)
        return enum_variant_index(node)
      end
      if (addr = gen_addr(node))
        return load_value(field_type(tt, node.field), addr, volatile: pointer_type?(tt) && tt.volatile)
      end
      if struct_type?(tt)
        s = gen_expr(node.target)
        idx = field_index(tt, node.field)
        return instr("extractvalue #{llvm_type(tt)} #{s}, #{idx}")
      end
      "void"
    end

    def gen_struct_init(node)
      decl = @structs[node.type_name]
      st = NamedType.new(0, 0, name: decl.name, resolved: decl)
      ptr = alloca(node.type_name, st)
      node.fields.each do |f|
        ft = field_type_for_decl(decl, f.name)
        fidx = field_index_for_decl(decl, f.name)
        v = f.value ? gen_as(f.value, ft) : gen_var(VarExpr.new(0, 0, name: f.name))
        ep = instr("getelementptr #{struct_name(decl.name)}, ptr #{ptr}, i64 0, i32 #{fidx}")
        store_value(ft, v, ep)
      end
      load_value(st, ptr)
    end

    def gen_if_expr(node)
      t = node.sema_type
      n = @bb += 1
      c = gen_as(node.cond, @sema.bool_type)
      emit_term("br i1 #{c}, label %ifx_then.#{n}, label %ifx_else.#{n}")
      emit_label("ifx_then.#{n}")
      v1 = gen_block_value(node.then_block, t)
      emit_branch_to("ifx_end.#{n}")
      pred1 = @cur_block
      emit_label("ifx_else.#{n}")
      v2 = gen_block_value(node.else_block, t)
      emit_branch_to("ifx_end.#{n}")
      pred2 = @cur_block
      emit_label("ifx_end.#{n}")
      instr("phi #{llvm_type(t)} [#{v1}, %#{pred1}], [#{v2}, %#{pred2}]")
    end

    def gen_block_value(block, t)
      push_scope
      stmts = block.stmts
      stmts[0...-1].each { |s| gen_stmt(s) }
      last = stmts.last
      v = last.is_a?(ExprStmt) ? gen_as(last.expr, t) : gen_as(last, t)
      pop_scope
      v
    end

    def gen_maybe_else(node)
      inner = node.sema_type
      n = @bb += 1
      s = gen_as(node.target, node.target.sema_type)
      ok = instr("extractvalue { i1, #{llvm_type(inner)} } #{s}, 0")
      val = instr("extractvalue { i1, #{llvm_type(inner)} } #{s}, 1")
      emit_term("br i1 #{ok}, label %m_ok.#{n}, label %m_else.#{n}")
      emit_label("m_else.#{n}")
      push_scope
      node.else_block.stmts.each { |st| gen_stmt(st) }
      pop_scope
      emit_label("m_ok.#{n}")
      val
    end

    def gen_unwrap(node)
      inner = node.sema_type
      n = @bb += 1
      s = gen_as(node.target, node.target.sema_type)
      ok = instr("extractvalue { i1, #{llvm_type(inner)} } #{s}, 0")
      val = instr("extractvalue { i1, #{llvm_type(inner)} } #{s}, 1")
      emit_term("br i1 #{ok}, label %uw_ok.#{n}, label %uw_err.#{n}")
      emit_label("uw_err.#{n}")
      emit_defers
      rt = @current_ret_type
      if rt && optional_type?(rt)
        r = instr("insertvalue #{llvm_type(rt)} zeroinitializer, i1 false, 0")
        conv = int_convert(val, inner, rt.inner)
        r = instr("insertvalue #{llvm_type(rt)} #{r}, #{llvm_type(rt.inner)} #{conv}, 1")
        emit_term("ret #{llvm_type(rt)} #{r}")
      else
        emit_term("ret void")
      end
      emit_label("uw_ok.#{n}")
      val
    end

    # addresses and helpers

    def volatile_through?(node)
      t =
        case node
        when UnaryExpr
          node.op == "*" ? node.operand.sema_type : nil
        when FieldAccessExpr, IndexExpr
          node.target.sema_type
        end
      t.is_a?(PointerType) && t.volatile
    end

    def gen_addr(node)
      case node
      when VarExpr
        if (loc = lookup_local(node.name))
          loc[:ptr]
        elsif @statics.key?(node.name)
          "@#{static_name(node.name)}"
        elsif (fn = @fns[node.name])
          return nil if port_io?(fn)
          "@#{fn_name(fn)}"
        else
          nil
        end
      when UnaryExpr
        if node.op == "*"
          t = node.operand.sema_type
          gen_as(node.operand, t)
        else
          nil
        end
      when IndexExpr
        tt = node.target.sema_type
        if slice_type?(tt)
          s = gen_expr(node.target)
          base = instr("extractvalue { ptr, i64 } #{s}, 0")
          idx = gen_as(node.index, usize_type)
          instr("getelementptr #{llvm_type(tt.elem)}, ptr #{base}, i64 #{idx}")
        elsif array_type?(tt)
          base = gen_addr(node.target)
          return nil if base.nil?
          idx = gen_as(node.index, usize_type)
          instr("getelementptr #{llvm_type(tt)}, ptr #{base}, i64 0, i64 #{idx}")
        elsif pointer_type?(tt)
          base = gen_expr(node.target)
          idx = gen_as(node.index, usize_type)
          instr("getelementptr #{llvm_type(tt.elem)}, ptr #{base}, i64 #{idx}")
        end
      when FieldAccessExpr
        tt = node.target.sema_type
        if pointer_type?(tt)
          base = gen_expr(node.target)
          idx = field_index(tt.elem, node.field)
          idx && instr("getelementptr #{struct_name(tt.elem.name)}, ptr #{base}, i64 0, i32 #{idx}")
        elsif struct_type?(tt)
          base = gen_addr(node.target)
          idx = field_index(tt, node.field)
          base && idx && instr("getelementptr #{struct_name(tt.name)}, ptr #{base}, i64 0, i32 #{idx}")
        end
      end
    end

    def field_type(tt, name)
      struct = tt.is_a?(PointerType) ? tt.elem : tt
      struct.resolved.fields.find { |f| f.name == name }.type
    end

    def field_index(tt, name)
      struct = tt.is_a?(PointerType) ? tt.elem : tt
      struct.resolved.fields.index { |f| f.name == name }
    end

    def field_index_for_decl(decl, name)
      decl.fields.index { |f| f.name == name }
    end

    def field_type_for_decl(decl, name)
      decl.fields.find { |f| f.name == name }.type
    end

    def enum_pattern_index(pat, st)
      decl =
        if pat.respond_to?(:type_name) && pat.type_name
          @enums[pat.type_name]
        else
          st.is_a?(NamedType) ? st.resolved : nil
        end
      name = pat.respond_to?(:variant) ? pat.variant : pat.field
      idx = decl.variants.index { |v| v.name == name }
      idx.to_s
    end

    def enum_variant_index(node)
      decl =
        if node.respond_to?(:type_name) && node.type_name
          @enums[node.type_name]
        else
          t = node.sema_type
          t.is_a?(NamedType) ? t.resolved : nil
        end
      name = node.respond_to?(:variant) ? node.variant : node.field
      idx = decl.variants.index { |v| v.name == name }
      idx.to_s
    end

    def usize_type
      PrimitiveType.new(0, 0, name: "usize")
    end

    def range_type(rng)
      s = rng.start.sema_type
      e = rng.end_.sema_type
      s_lit = rng.start.is_a?(IntLiteral) || rng.start.is_a?(FloatLiteral)
      e_lit = rng.end_.is_a?(IntLiteral) || rng.end_.is_a?(FloatLiteral)
      return s if e_lit
      return e if s_lit
      s
    end
  end
end
